CREATE TABLE [dbo].[Message]
(
	[Id] UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID(),
	[Title] NVARCHAR(50) NOT NULL,
	[Content] NVARCHAR(1000) NOT NULL,
	[DateMessage] DATETIME2 NOT NULL DEFAULT GETDATE(),
	[UserAppId] UNIQUEIDENTIFIER NULL,
	CONSTRAINT PK_Message PRIMARY KEY([Id]),
	CONSTRAINT FK_Message_User FOREIGN KEY([UserAppId]) 
		REFERENCES [UserApp]([Id])
		ON DELETE SET NULL
)
