CREATE TABLE [dbo].[UserApp]
(
	[Id] UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID(),
	[Email] NVARCHAR(250) NOT NULL,
	[Username] NVARCHAR(50) NOT NULL,
	[Password] VARBINARY(64) NOT NULL,
	[Salt] NVARCHAR(100) NOT NULL,
	[IsAdmin] BIT NOT NULL DEFAULT 0, 
    CONSTRAINT PK_UserApp PRIMARY KEY([Id]),
	CONSTRAINT UK_UserApp_Email UNIQUE ([Email]),
	CONSTRAINT UK_UserApp_Username UNIQUE ([Username])
)
